# Generated by Django 2.1.7 on 2019-07-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20190624_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='lifts',
        ),
    ]
