# Generated by Django 2.1.7 on 2019-07-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_program_lifts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lift',
        ),
    ]
